### PR TITLE
Import content from N3PDF/external

### PR DESCRIPTION
**Pull request by alecandido**
See https://github.com/NNPDF/pineko/pull/25#issuecomment-1267113417

### CODE REVIEW

**Comment by AleCandido** [comment]
> let's not port backup stuff ...

Unfortunately, without that FONLLdis is not working out of the box. If you wish you can find another solution (maybe it is really simple, but I have no time at the moment).

The moment we have a solution, we can also remove from history, and keep the repo free of that junk, however:
```
drwxrwxr-x    - alessandro  4 ott 17:04 packages/.backup
.rw-rw-r-- 1,9M alessandro  4 ott 17:04 ├── FONLLdis.tar.gz
.rw-rw-r--  316 alessandro  4 ott 17:04 ├── update.sh
.rw-rw-r--  17k alessandro  4 ott 17:04 └── xspace-bench.tar.gz
```

So, for xspace-bench is really negligible, and FONLLdis has the size of a picture, and not going to increase. Everything else I removed, as you can see.
For me would be much nicer (since cleaner) to remove it, but it's definitely not worth my effort, given limited resources.

**Comment by felixhekhorn** [comment]
I perfectly agree - I wasn't aware it is actually used ... keep it (maybe rename it?)

**Comment by AleCandido** [comment]
Do what you prefer. I don't really have a better name :)

**Comment by felixhekhorn** [comment]
`legacy`? (without any leading `.`)

**Comment by AleCandido** [comment]
> `legacy`? (without any leading `.`)

Not really, there is nothing legacy: that is the actual FONLLdis, and not going to change...

**Comment by felixhekhorn** [comment]
`local_codes`?

**Comment by AleCandido** [comment]
Still prefer `.backup`. It is a back-up of the code...

**Comment by felixhekhorn** [comment]
> Still prefer `.backup`. It is a back-up of the code...

They are not. That's what me confused in the first place - they are the one and only source of truth. `external`? Or at least remove the leading `.` or else I give up

**Comment by AleCandido** [comment]
> they are the one and only source of truth

Nope, it's a dirty trick. The source of truth is `NNPDF/external`.

And I would use that one, but it is a private repo, and it might cause issues in many situations. That's why I needed a `.backup`.

**Pull request merged**
